// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZr4Pv6FnxthfjqCpLcW7m45ZFSVeWiY8',
    appId: '1:227036738108:web:ca388b60aa6d7198764939',
    messagingSenderId: '227036738108',
    projectId: 'tiktok1-42f6b',
    authDomain: 'tiktok1-42f6b.firebaseapp.com',
    storageBucket: 'tiktok1-42f6b.appspot.com',
    measurementId: 'G-8JMKGTXNF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLrHNCMz8ZQS8ZhvgNvrDbDVBLn2u5aLM',
    appId: '1:227036738108:android:f7618de39f45be4d764939',
    messagingSenderId: '227036738108',
    projectId: 'tiktok1-42f6b',
    storageBucket: 'tiktok1-42f6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTdfDdL8r3CA8whMa7BaRNTyv4B5EaYCs',
    appId: '1:227036738108:ios:cc0b129185a22e01764939',
    messagingSenderId: '227036738108',
    projectId: 'tiktok1-42f6b',
    storageBucket: 'tiktok1-42f6b.appspot.com',
    iosClientId: '227036738108-erm2k2v0l0cqs9s7mnhlhbupm1tonvar.apps.googleusercontent.com',
    iosBundleId: 'com.domain.tiktok',
  );
}
